// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Mittens.Memory.Data.Compiled
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("123ff113-e0cc-44e4-abc9-623a8cf03df4"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var fact = FactEntityType.Create(this);

            FactEntityType.CreateAnnotations(fact);

            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:DefaultSchema", "mittens");
        }
    }
}
