// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Mittens.Memory.Data;
using Mittens.Memory.Data.Compiled;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
