// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace AotMemoryServer.Data.Compiled
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("2e99a6bb-494f-441b-bdbe-599907443a61"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var memoryFact = MemoryFactEntityType.Create(this);

            MemoryFactEntityType.CreateAnnotations(memoryFact);

            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:DefaultSchema", "mem");
        }
    }
}
